export const exampleNames = [
  'Abigail Adams',
  'Alice Childress',
  'Alice Paul',
  'Alicia Dickerson Montemayor',
  'Amelia Earhart',
  'Amelia Boynton Robinson',
  'Anne Bradstreet',
  'Annie Dodge Wauneka',
  'Annie Jump Cannon',
  'Babe Didrikson Zaharias',
  'Belva Lockwood',
  'Bessie Coleman',
  'Betty Ford',
  'Biddy Mason',
  'Carrie Chapman Catt',
  'Chien-Shiung Wu',
  'Christa Mcauliffe',
  'Clara Barton',
  'Coretta Scott King',
  'Daisy Gatson Bates',
  'Dorothea Dix',
  'Edmonia Lewis',
  'Eleanor Roosevelt',
  'Elizabeth Blackwell',
  'Elizabeth Peratrovich',
  'Elizabeth Cady Stanton',
  'Ellen Swallow Richards',
  'Emma Lazarus',
  'Emma Willard',
  'Esther Martinez',
  'Eunice Kennedy Shriver',
  'Fabiola Cabeza De Baca Gilbert',
  'Fannie Lou Hamer',
  'Felisa Rincon De Gautier',
  'Florence Chadwick',
  'Frances Willard',
  'Georgia Okeeffe',
  'Gertrude Stein',
  'Grace Hopper',
  'Harriet Tubman',
  'Harriet Beecher Stowe',
  'Hedy Lamarr',
  'Helen Keller',
  'Henrietta Swan Leavitt',
  'Hetty Green',
  'Ida B. Wells-Barnett',
  'Irene Morgan Kirkaldy',
  'Jane Addams',
  'Jane Cunningham Croly',
  'Jane Johnston Schoolcraft',
  'Jovita Idár',
  'Julia Ward Howe',
]